# =====================================================================
#  gen_cnfont.ps1  -  build the 16x16 CJK bitmap font used by the UI
#
#  It scans src/*.cpp + include/*.h for every character with a codepoint
#  > 0x7F and renders each one with a Windows CJK font (SimSun) into a
#  16x16 1-bpp bitmap, then writes src/cnfont_data.cpp.
#
#  Re-run this whenever you add / change Chinese text in the sources:
#     powershell -ExecutionPolicy Bypass -File tools/gen_cnfont.ps1
# =====================================================================
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root    = Split-Path -Parent $PSScriptRoot          # project root
$srcdir  = Join-Path $root 'src'
$incdir  = Join-Path $root 'include'
$outFile = Join-Path $srcdir 'cnfont_data.cpp'

# ---- 1. collect every non-ASCII codepoint used in the sources ---------
$text = ''
Get-ChildItem $srcdir, $incdir -Include *.cpp, *.h -File -Recurse |
  Where-Object { $_.Name -ne 'cnfont_data.cpp' } |
  ForEach-Object { $text += [System.IO.File]::ReadAllText($_.FullName) + "`n" }

$codes = @{}
foreach ($ch in $text.ToCharArray()) {
  $cp = [int][char]$ch
  if ($cp -gt 0x7F -and $cp -ne 0xFEFF) { $codes[$cp] = $true }
}
$all = $codes.Keys | Sort-Object

# ---- 2. render each glyph to a 16x16 bitmap ---------------------------
$font  = New-Object System.Drawing.Font('SimSun', 16, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$hint  = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit

$blob  = New-Object System.Collections.Generic.List[byte]
$table = New-Object System.Collections.Generic.List[string]
$idx   = 0

foreach ($cp in $all) {
  $bmp = New-Object System.Drawing.Bitmap 16, 16
  $g   = [System.Drawing.Graphics]::FromImage($bmp)
  $g.Clear([System.Drawing.Color]::Black)
  $g.TextRenderingHint = $hint
  $g.DrawString([string][char]$cp, $font, [System.Drawing.Brushes]::White, -1, -1)
  for ($y = 0; $y -lt 16; $y++) {
    $hi = 0; $lo = 0
    for ($x = 0; $x -lt 16; $x++) {
      $bit = 0
      if ($bmp.GetPixel($x, $y).R -gt 127) { $bit = 1 }
      if ($x -lt 8) { $hi = $hi -bor ($bit -shl (7 - $x)) }
      else          { $lo = $lo -bor ($bit -shl (15 - $x)) }
    }
    $blob.Add([byte]$hi)
    $blob.Add([byte]$lo)
  }
  $table.Add(('{{0x{0:X4},{1}}}' -f $cp, $idx))
  $idx++
  $g.Dispose(); $bmp.Dispose()
}
$font.Dispose()

# ---- 3. emit C++ ------------------------------------------------------
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// AUTO-GENERATED by tools/gen_cnfont.ps1  -  DO NOT EDIT BY HAND')
[void]$sb.AppendLine('#include "cnfont.h"')
[void]$sb.AppendLine('')
[void]$sb.AppendLine(('const uint16_t CN_COUNT = {0};' -f $idx))
[void]$sb.AppendLine('')
# table (wrapped ~10 per line)
[void]$sb.AppendLine('const CNGlyph CN_TABLE[] = {')
for ($i = 0; $i -lt $table.Count; $i += 10) {
  $chunk = $table[$i..([Math]::Min($i + 9, $table.Count - 1))] -join ','
  [void]$sb.AppendLine('  ' + $chunk + ',')
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('')
# blob
[void]$sb.AppendLine('const uint8_t CN_BLOB[] = {')
for ($i = 0; $i -lt $blob.Count; $i += 16) {
  $chunk = ($blob[$i..([Math]::Min($i + 15, $blob.Count - 1))] | ForEach-Object { $_.ToString() }) -join ','
  [void]$sb.AppendLine('  ' + $chunk + ',')
}
[void]$sb.AppendLine('};')

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("cnfont: {0} glyphs -> {1}" -f $idx, $outFile)
